id: I3E5590E1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:51:54+00:00'
last_modified: '2022-06-08T10:38:45.696028+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29252
  title: ཕ་བོང་ཁ་པའི་སློབ་མའི་དགག་ལན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9818':
      image_group_id: I5248
      title: ''
      total_pages: 482
      order: 1
      base_file: 9818.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
